version: '3.8'

services:
  mcp-browser-tools:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    container_name: gnios-mcp-browser-tools
    ports:
      - '3001:3001'
    volumes:
      - ./logs:/app/logs
      - ./mcp-browser-setup.js:/app/mcp-browser-setup.js
    environment:
      - NODE_ENV=production
      - MCP_PORT=3001
      - LOG_LEVEL=info
    restart: unless-stopped
    networks:
      - mcp-network

  # Serviço opcional para visualizar logs
  mcp-log-viewer:
    image: nginx:alpine
    container_name: gnios-mcp-log-viewer
    ports:
      - '8080:80'
    volumes:
      - ./logs:/usr/share/nginx/html/logs:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mcp-browser-tools
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

volumes:
  mcp-logs:
    driver: local
